### login User 1
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "john_doe",
  "password": "password123"
}


### login User 2
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "mike_wilson",
  "password": "mikePass789"
}